// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB24S2AIetIUWkHWdn5rJ6CUokeISpEY6s',
    appId: '1:566425298962:web:f543fc772770247d5f50cb',
    messagingSenderId: '566425298962',
    projectId: 'model-ia-f8539',
    authDomain: 'model-ia-f8539.firebaseapp.com',
    storageBucket: 'model-ia-f8539.firebasestorage.app',
    measurementId: 'G-XVCVEZFLR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9AZnaAzXN5yMFpaFwUYkrO6D-B-4pLZ4',
    appId: '1:566425298962:android:76e1c515ee6582c55f50cb',
    messagingSenderId: '566425298962',
    projectId: 'model-ia-f8539',
    storageBucket: 'model-ia-f8539.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB24S2AIetIUWkHWdn5rJ6CUokeISpEY6s',
    appId: '1:566425298962:web:c6640a95d4b3e7625f50cb',
    messagingSenderId: '566425298962',
    projectId: 'model-ia-f8539',
    authDomain: 'model-ia-f8539.firebaseapp.com',
    storageBucket: 'model-ia-f8539.firebasestorage.app',
    measurementId: 'G-J4KK5TL5E5',
  );

}